// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKDP0jqdCgka7Yv3bVz6YyEMNhaVI1FrM',
    appId: '1:1097173323032:web:d242a8a2e9e94fc4f6226d',
    messagingSenderId: '1097173323032',
    projectId: 'foodease-aebf2',
    authDomain: 'foodease-aebf2.firebaseapp.com',
    storageBucket: 'foodease-aebf2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeHR8QUyscqFlXbne3sea2l2rBj11wd-s',
    appId: '1:1097173323032:android:3d8f3b1cddf109eef6226d',
    messagingSenderId: '1097173323032',
    projectId: 'foodease-aebf2',
    storageBucket: 'foodease-aebf2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjBM1qpzOK4mcm1r0rb48bCTDfK-ym_-4',
    appId: '1:1097173323032:ios:f08ef81bda8ea6d8f6226d',
    messagingSenderId: '1097173323032',
    projectId: 'foodease-aebf2',
    storageBucket: 'foodease-aebf2.appspot.com',
    iosClientId: '1097173323032-umtqqkef04cfor28aik6f88geqkl4nkn.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjBM1qpzOK4mcm1r0rb48bCTDfK-ym_-4',
    appId: '1:1097173323032:ios:f08ef81bda8ea6d8f6226d',
    messagingSenderId: '1097173323032',
    projectId: 'foodease-aebf2',
    storageBucket: 'foodease-aebf2.appspot.com',
    iosClientId: '1097173323032-umtqqkef04cfor28aik6f88geqkl4nkn.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
